name: TP_CI_CD Sum

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  merge:
    runs-on: ubuntu-latest
    needs: test
    if: success()

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Configure git
        run: |
          git config user.name 'Kevin-Lamotte974'
          git config user.email 'kevinlamotte974@gmail.com'
          git config pull.rebase false 

      - name: Merge dev into main
        run: |
          git fetch --all
          git checkout main
          git merge origin/dev --no-ff

      - name: Push changes to main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main

  # deploy: 
  #     runs-on: ubuntu-latest
  #     needs: test
  #     steps:
  #       - name: Checkout repository
  #         uses: actions/checkout@v3

  #       - name: Login to Heroku
  #         env:
  #           HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  #         run: |
  #           echo "machine api.heroku.com login=$HEROKU_EMAIL password=$HEROKU_API_KEY" > ~/.netrc
  #           echo "machine git.heroku.com login=$HEROKU_EMAIL password=$HEROKU_API_KEY" >> ~/.netrc
  #           heroku git:remote -a <nom_de_ton_app_heroku>

  #       - name: Deploy to Heroku
  #         run: git push heroku main